[package]

name = "ordered-float"
version = "0.0.2"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
license = "MIT"
description = "Wrappers for total ordering on floats."
repository = "https://github.com/reem/rust-ordered-float"

[dependencies]
num = { version = "0.1", default_features = false }

[dev-dependencies]
stainless = "*"

